/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ffijava;

import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.SymbolLookup;
import java.lang.foreign.ValueLayout;

public class App {

    public static void main(String[] args) {
        var linker = Linker.nativeLinker();
        SymbolLookup lookup = linker.defaultLookup();
        var getpid = linker.downcallHandle(
                lookup.lookup("getpid").get(),
                FunctionDescriptor.of(ValueLayout.JAVA_INT));
        try {
            System.out.println("PID " + getpid.invoke());
        } catch (Throwable e) {
            e.printStackTrace(System.err);
        }
    }
}
